version: '3'

networks:
  laravel:

services:
  isir_explorer_web:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
    container_name: isir_nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - isir_php
    networks:
      - laravel

  isir_php:
    build:
      context: .
      dockerfile: ./docker/php/php.dockerfile
    container_name: isir_php
    volumes:
      - .:/var/www/html:delegated
    networks:
      - laravel

  isir_composer:
    build:
      context: .
      dockerfile: ./docker/composer/composer.dockerfile
    container_name: isir_composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - isir_php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

