version: '3'

volumes:
  www-volume:

networks:
  laravel:

services:
  isir_explorer_web:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
    container_name: isir_nginx
    ports:
      - 8080:80
    volumes:
      - www-volume:/var/www/html
    depends_on:
      - isir_php
    networks:
      - laravel

  isir_php:
    build:
      context: .
      dockerfile: ./docker/php/php.dockerfile
    container_name: isir_php
    volumes:
      - www-volume:/var/www/html
    networks:
      - laravel

  isir_npm:
    user: 1002:1002
    image: node:13.7
    container_name: npm
    volumes:
      - www-volume:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm', 'run', 'prod']
    networks:
      - laravel

  isir_composer:
    user: 1002:1002
    build:
      context: .
      dockerfile: ./docker/composer/composer.dockerfile
    container_name: isir_composer
    volumes:
      - www-volume:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - isir_php
    user: laravel
    entrypoint: ['composer', 'install']
    networks:
      - laravel



